### ISSUE TITLE
個別食料の栄養素ページ

### ISSUE THREAD

**Issue by dandan611** [Smart-SE/sse2019-group5#10]

**Comment by dandan611** [comment]
こんなイメージ　【あすけん】
![Screenshot_20190622-144410](https://user-images.githubusercontent.com/7886577/59960064-07341000-94fd-11e9-867e-17ebee1d4f3b.jpg)

**Comment by tomita32** [comment]
[SCR_21_detail.xlsx](https://github.com/Smart-SE/sse2019-group5/files/3323197/SCR_21_detail.xlsx)

**Comment by sakai-memoru** [comment]
富田さん

画面レイアウトのアップ、ありがとうございます。

坂井の方で、サンプルデータの生成などで、少しExcelをいじったので、
GitHubにコミットしました。


各位

作成した画面レイアウトは、コミットしてくださいね

余裕のある方は、画面のHTML作成のチケットを作成しておきましたので、
そのチケットを、自発的に取得して、作業を進めて下さいね

Sent from Mail for Windows 10

**Comment by sakai-memoru** [comment]
各位

設計書ですが、皆さん、ISSUEに添付していたものは、
名前を変えて、Githubのレポジトリに、坂井の方でアップしました。

今後は、レポジトリの方で、共有しましょう。
Issueだと、どれが最新だかわからなくなるので・・・・




Sent from Mail for Windows 10

From: memoru
Sent: 27 June 2019 17:39
To: Smart-SE/sse2019-group5; Smart-SE/sse2019-group5
Cc: Subscribed
Subject: RE: [Smart-SE/sse2019-group5] 個別食料の栄養素ページ (#10)

富田さん

画面レイアウトのアップ、ありがとうございます。

坂井の方で、サンプルデータの生成などで、少しExcelをいじったので、
GitHubにコミットしました。


各位

作成した画面レイアウトは、コミットしてくださいね

余裕のある方は、画面のHTML作成のチケットを作成しておきましたので、
そのチケットを、自発的に取得して、作業を進めて下さいね

Sent from Mail for Windows 10
