### ISSUE TITLE
調査：Bootstrapでのモーダル操作

### ISSUE THREAD

**Issue by sakai-memoru** [Smart-SE/sse2019-group5#12]
Bootstrapでモーダル表示の仕方の技術調査

**Comment by sakai-memoru** [comment]
モーダルで呼び出しサンプルを作成した。

モーダルダイアログ呼び出しをクリックください。
https://smart-se.github.io/sse2019-group5/index.html

**Comment by sakai-memoru** [comment]
reference 

 Bootstrap3日本語リファレンスJavaScriptモーダルa要素で呼び出す
a要素で呼び出す
a要素でモーダル・ダイアログを呼び出すサンプル。
http://bootstrap3.cyberlab.info/javascript/modals-a.html

**Comment by dandan611** [comment]
おー、すげー。今更確認ですが…モーダル・ダイアログ表示いい感じですね。

**Comment by dandan611** [comment]
終わっているので閉じます
