### ISSUE TITLE
[HTML作成] 確認/発注ページ

### ISSUE THREAD

**Issue by sakai-memoru** [Smart-SE/sse2019-group5#14]
確認/発注ページの画面レイアウトをもとに、HTMLを作成する。

**Comment by dandan611** [comment]
![m-d_h-n-s_4o-01](https://user-images.githubusercontent.com/7886577/60753000-cc0b0400-a007-11e9-961d-bcdedac6df8b.png)

**Comment by dandan611** [comment]
マージされたので閉じます

**Comment by dandan611** [comment]
イメージこんな感じ
![m-d_h-n-s_16o-00](https://user-images.githubusercontent.com/7886577/60764284-da1d5b00-a0c1-11e9-9017-bc6e0e9516c0.png)

**Comment by dandan611** [comment]
あ、間違えた(笑)
