### ISSUE TITLE
[HTML作成] レコメンドページ

### ISSUE THREAD

**Issue by sakai-memoru** [Smart-SE/sse2019-group5#15]
レコメンドページの画面レイアウトをもとに、HTMLを作成する。

**Comment by dandan611** [comment]
こんな感じ
![m-d_h-n-s_16o-00](https://user-images.githubusercontent.com/7886577/60764325-531cb280-a0c2-11e9-8bee-05de46c52e3c.png)

**Comment by okumura-sse0218** [comment]
dandanさん
チェックボックスと変更するボタンは今回実装しなくなった感じです。
specのSCR_03_recommend.xlsx　画面項目シートをご参照ください。

**Comment by dandan611** [comment]
おーほんとだ(笑)画面イメージだけみてました。
他何かあります？

**Comment by okumura-sse0218** [comment]
画像を見る限り特にないです。完璧です...ｶﾞｸｶﾞｸ((( ;ﾟДﾟ)))ﾌﾞﾙﾌﾞﾙ

**Comment by dandan611** [comment]
マージしたので閉じます。
