### ISSUE TITLE
[HTML作成] 個別食料の栄養素ページ

### ISSUE THREAD

**Issue by sakai-memoru** [Smart-SE/sse2019-group5#16]
個別食料の栄養素ページの画面レイアウトをもとに、HTML/Javascriptを作成する。

**Comment by dandan611** [comment]
貰います。
ある一つのコースの栄養素表示という想定で作成します。

関連チケットは下記です。
* #10

**Comment by dandan611** [comment]
一旦優先度を下げてレコメンドページができてからモーダルでくっつける形にする。

**Comment by dandan611** [comment]
レコメンドページが終わってから着手する
