### ISSUE TITLE
7/13 デモ発表用の補足資料を作る

### ISSUE THREAD

**Issue by dandan611** [Smart-SE/sse2019-group5#21]
対象と価値の説明用
パワポ数枚程度

**Comment by tomita32** [comment]
最低限ですけど、とりあえず発表の流れを作成しました。
[デモ用説明資料.pptx](https://github.com/Smart-SE/sse2019-group5/files/3365936/default.pptx)

**Comment by dandan611** [comment]
作成ありがとうございます。
キャンバスとストーリーに並びがわかって良いですね。
そこから先はデモで何とかしましょう。

**Comment by dandan611** [comment]
[default.pptx](https://github.com/Smart-SE/sse2019-group5/files/3377153/default.pptx)

**Comment by tomita32** [comment]
昨日の議論を踏まえて、少しだけスライドを整理しました。
[K1_gropu5_Presentation.pptx](https://github.com/Smart-SE/sse2019-group5/files/3380254/K1_gropu5_Presentation.pptx)

**Comment by dandan611** [comment]
おー、大分質が良くなってますね。
詳細の仕様がかわるかもなのでそこは金曜日にみんなで見ながら直しましょうー

**Comment by sakai-memoru** [comment]
本日07/11木曜日ではなく、
明日07/12金曜日に、集合でしたっけ？

Sent from Mail for Windows 10

**Comment by dandan611** [comment]
いえいえ、集まるのは今日です。たしか金曜空いてないですよね。
直すなら前日かなというくらい

**Comment by sakai-memoru** [comment]
了解です。

Sent from Mail for Windows 10

**Comment by tomita32** [comment]
遅くなりすいません。少し絵を入れました。
[K1_group5_Presentation.pptx](https://github.com/Smart-SE/sse2019-group5/files/3385413/K1_group5_Presentation.pptx)

**Comment by sakai-memoru** [comment]
GitHubにアップも

Sent from Mail for Windows 10

**Comment by tomita32** [comment]
Close
