### ISSUE TITLE
ユーザーストーリーに合わせてUIを修正する

### ISSUE THREAD

**Issue by dandan611** [Smart-SE/sse2019-group5#32]
**修正点は下記**
* トップページをhistoryにする(history をindex に名称変更してhistory ファイルを消す)
* historyページにrecommendボタンを追加する
* recommendに推薦コース全体の栄養バランスボタンとページを追加する(ポップアップ)
* recommend のNoの項目は、「朝食」、「昼食」、「夕食」の食事時間とする
* リンクがついてないところはリンクを張りなおす

**Comment by okumura-sse0218** [comment]
坂井さん
お願いします！

**Comment by sakai-memoru** [comment]
修正を完了しました。
