### ISSUE TITLE
[recommend.html] 発表までの最低限の処理を完成させる

### ISSUE THREAD

**Issue by okumura-sse0218** [Smart-SE/sse2019-group5#35]
・各メニューの栄養ボタンの文字色を白にする。
・右上に発注ボタンを移動
・右上に1week分の栄養をみる栄養ボタンを追加する。

・下記のrecommendからデータをとって表示する。
https://smart-se.github.io/sse2019-group5/spec/API_index.html
※json-serverの起動が必要。
https://github.com/Smart-SE/sse2019-group5/blob/master/docs/1907-json-server-installation.md

**Comment by okumura-sse0218** [comment]
坂井さん

お願いします！

**Comment by sakai-memoru** [comment]
修正を完了しました。
