### ISSUE TITLE
バックエンド概要設計を行う

### ISSUE THREAD

**Issue by dandan611** [Smart-SE/sse2019-group5#5]

**Comment by sakai-memoru** [comment]
==============================
以下の手順で、データを作成することで考えます。
①各画面ごとに、対応するデータをまず、Excelで作る
- purchase
- history
- recommend
- detail ◆済  /ingregients

②対象のExcelデータを、json形式に変換する
https://www.csvjson.com/csv2json

③jsonに変換したデータを、json-serverのデータ（db.json）に反映する
④当該のjson-severには、id指定で１件ずつか、page指定で20件ずつ取得する

＝＝＝＝＝＝＝＝＝＝＝＝
REST APIのパス
/purchase
/history
/recommend
/ingregients

**Comment by sakai-memoru** [comment]
REST APIは、json-serverパッケージで実装する。以下、手順。

JSON-Serverの説明文
https://github.com/Smart-SE/sse2019-group5/blob/master/docs/1907-json-server-installation.md

**Comment by sakai-memoru** [comment]
クローズします。
