### ISSUE TITLE
画面テンプレートの詳細設計

### ISSUE THREAD

**Issue by dandan611** [Smart-SE/sse2019-group5#6]
関連チケット：#4

**Comment by sakai-memoru** [comment]
以下、利用するbootstrapのtemplate
https://github.com/Smart-SE/sse2019-group5/wiki/1906-template-layout-sample

**Comment by sakai-memoru** [comment]
テンプレートをgit reposに反映。
動作は、GitHub Pageを参照ください。

https://smart-se.github.io/sse2019-group5/index.html

Closeします。
