### ISSUE TITLE
[layout]レコメンドページの詳細設計

### ISSUE THREAD

**Issue by dandan611** [Smart-SE/sse2019-group5#8]

**Comment by okumura-sse0218** [comment]
[画面設計_レコメンド画面.xlsx](https://github.com/Smart-SE/sse2019-group5/files/3316627/_.xlsx)

**Comment by okumura-sse0218** [comment]
表示項目まだ書いていないですがいったんアップしました。

**Comment by okumura-sse0218** [comment]
コミットしました。
eefcf90a1ab4e38ffd27f50e47e6c67133bb64a8

**Comment by dandan611** [comment]
@okumura-sse0218 さん、このチケットはみんなでもう確認したので、Closeしてよいですよー。

**Comment by dandan611** [comment]
終わっているので閉じます。
